# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: 'Build and Test'
            script:
              - echo "Your build and test goes here..."
        - step:
            name: 'Lint'
            script:
              - echo "Your linting goes here..."
        - step:
            name: 'Security scan'
            script:
              - echo "Your security scan goes here..."
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
    - step:
        name: 'Clone and Sync with GitHub'
        script:
          # SSH 방식으로 변경된 GitHub 저장소 URL
          - git clone git@github.com:minnaaa/sveltedemo.git
          - cd sveltedemo
          # Bitbucket에서 생성한 SSH 키를 GitHub에 등록했는지 확인
          # git remote add 및 git pull/push 명령어는 SSH URL을 사용할 때 변경할 필요가 없지만, 저장소 URL이 SSH 형식으로 바뀌어야 함
          - git config --global pull.rebase false
          - git config user.name "sonmina"
          - git config user.email "sonmina0115@gmail.com"
          - git pull origin main --allow-unrelated-histories
          - git push origin main