# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
        - echo "Your deployment to staging script goes here..."
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
    - step:
        name: 'Deploy to Cloudflare Pages'
        script:
          - zip -r build.zip \Users\user\test3 
          - apt-get update && apt-get install -y curl
          - |
            curl --request POST \
            --url "https://api.cloudflare.com/client/v4/accounts/b5bca0c03c2724360edfe745838ad046/pages/projects/sveltedemo/deployments" \
            --header "Authorization: Bearer bj0oRyZ9i0_Vf0qM_MUoNFvdMLAPxHN-ecdt9Nfx" \
            --header 'Content-Type: multipart/form-data' \
            --form 'files=@path/to/build.zip'
            --form 'branch=your-branch-name-here'
    - step:
        name: 'Sync with GitHub'
        script:
          - git remote add github git@github.com:minnaaa/sveltedemo.git
          - git config --global pull.rebase false 
          - git config user.name "sonmina" 
          - git config user.email "sonmina0115@gmail.com" 
          - git add .
          - git push github main